name: mobile_pbl
description: "A new Flutter project."
publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  dio: ^5.2.1
  intl: ^0.20.1
  image_picker: ^1.1.2
  open_file: ^3.5.10
  path_provider: ^2.1.5
  file_picker: ^8.1.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/home.png
    - assets/icons/progress.png
    - assets/icons/update.png
    - assets/icons/nonjti.png
    - assets/icons/dasar.png
    - assets/default.jpg
