name: mobile_pbl
description: "A new Flutter project."
publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.3.0
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  dio: ^5.2.1
  flutter_secure_storage: ^8.0.0


    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/home.png
    - assets/icons/progress.png
    - assets/icons/update.png
    - assets/icons/nonjti.png
